version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fundit-app:dev
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: fundit
      DB_USERNAME: fundit
      DB_PASSWORD: fundit
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: database
      REDIS_HOST: redis
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fundit
      MYSQL_DATABASE: fundit
      MYSQL_USER: fundit
      MYSQL_PASSWORD: fundit
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql-data:
  redis-data:
